Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Folder:
            - 'NodeTypes/*'
            - 'NodeTypes/Document/*'
    fusion:
      autoInclude:
        NeosRulez.Folder: true